- hosts: "{{ cli_target|default('all') }}"
  # collections:
  #   - acme.base
  roles:
    - acme.base.ntp_timezone
    - acme.base.apt_update
    - acme.base.ssh
    - acme.base.users
    - acme.base.iptables_global