- name: Configure repos
  ansible.builtin.template:
    src: sources.list.j2
    dest:  /etc/apt/sources.list

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes