- name: Add docker repo
  ansible.builtin.template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list

- name: Add docker repo keys
  ansible.builtin.apt_key:
    data: "{{ lookup('file', '../templates/docker.gpg') }}"

- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-compose-plugin
    update_cache: yes